
/*const letraIngresada = [
    {
        letra:"H",
        cantidad: 1,
    },
    {
        letra: "E",
        cantidad:"2",
    }
];
*/

const arrayDebut = [
    "TIM MCGRAW",
    "TEAR DROPS",
    "ON MY GUITAR",
    "OUR SONG",
    "FEELING LUCKY",
    "SMALL TOWN GIRL",
    "STAY BEAUTIFUL",
    "READY TO FLY",
    "OH MY MY MY",
    "PICTURE TO BURN",
    "SHOULDVE SAID NO",
    "COLD AS YOU",
    "UNTOUCHABLE",
];    

const arrayFearless = [
    "FEARLESS",
    "LOVE STORY",
    "JUM THEN FALL",
    "HEY STEPHEN",
    "SUPERSTAR",
    "BREATH",
    "THE BEST DAY",
    "ROMEO",
    "JULIET",
    "FIFTEEN",
    "WHITE HORSE",
    "U BELONG WITH ME",
    "TELL ME WHY",
    "CHANGE",
    "UNTOUCHABLE",
    "YOU ALL OCWE ME",
    "MR PERFECTLY FINE",
    "BYE BYE BABY",
];

const arraySPNow = [
    "LAST KISS",
    "SPARKS FLY",
    "MEAN",
    "NEVER GROW UP",
    "DEAR JOHN",
    "INNOCENT",
    "ENCHANTED",
    "HAUNTED",
    "LONG LIVE",
    "BETTER THAN REVENGE",
    "THE STORY OF US",
    "WONDERSTRUCK",
    "REVENGE",
    "BE BRAND NEW",
    "HA HA",
    "SPEAK NOW",
    "FUCK JOHN",
    "NEXT CHAPTER",
    "MINE",
    "TIMELESS",
    "I CAN SEE YOU",
    "OURS",
    "DROP EVERYTHING NOW",
    "FLIGHT RISK",
    "FIGHTING DRAGONS",
    "SUPERMAN",
    "INNOCENT",
    "FOOLISH ONE",
    "CASTLES CRUMBLING",
    "STAY LITTLE",
    "ELECTRIC TOUCH",
];

const arrayRed = [
    "STATE OF GRACE",
    "RED",
    "TREACHEROUS",
    "FUCK THE PATRIARCHY",
    "I KNEW YOU WERE TROUBLE",
    "ALL TOO WELL",
    "I ALMOST DO",
    "LIKE NEVER",
    "STAY",
    "THE LAST TIME",
    "HOLY GROUND",
    "THE LUCKY ONE",
    "SAD BEAUTIFUL TRAGIC",
    "STARLIGHT",
    "BEGIN AGAIN",
    "RONAN",
    "GIRL AT HOME",
    "STATE OF GRACE",
    "BETTER MAN",
    "NOTHING NEW",
    "BABE",
    "FOREVER WINTER",
    "RUN",
    "THE VERY FIRST TIME",
    "COME BACK",
    "BE HERE",
    "SAFE & SOUND",
    "WHOS TS ANYWAY",
    "TROUBLE",
    "BURNING RED",
    "SHES INSANE",
    "IT WAS RARE",
    "CASUALLY CRUEL",
    "I ALMOST DO",
];

const array1989 = [
    "SLUT",
    "WELCOME TO NY",
    "STYLE",
    "OUT OF THE WOODS",
    "BLANK SPACE",
    "STAY",
    "JAMES DEAN",
    "DAYDREAM LOOK",
    "GOOD GIRL FAITH",
    "SUBURBAN LEYENDS",
    "NICE TO MEET YOU",
    "MAGIC",
    "MADNESS",
    "SCREAMING CRYING",
    "RUMOURS FLY",
    "SO ITS GONNA BE FOREVER",
    "LIST OF EX LOVERS",
    "IS IT OVER NOW",
    "SAY DONT GO",
    "YOU LOVE THE GAME",
    "YOUNG AND RECLKESS",
    "WITH A NASTY SCAR",
    "SHAKE IT OFF",
    "I WISH YOU WOULD",
    "BAD BLOOD",
    "WILDEST DREAMS",
    "GET THE GIRL",
    "THIS LOVE",
    "CLEAN",
    "I KNOW PLACES",
    "WONDERLAND",
    "YOU ARE INLOVE",
    "NEW ROMANTICS",
    "RED LIPS",
    "ROSY CHEEKS",
    "NOTHING LAST FOREVER",
    "HANDSOME AS HELL",
    "I TS",
    "STARBUCKS LOVER",
    "NICE IS BETTER",
    "RED CLASSIC THING",
    "CHERRY LIPS",
    "CRYSTAL SKYIES",
    "NEXT MISTAKE",
    "WANNA PLAY",
    "THIS SICK BEAT",
    "NICE DRESS",
    "I WANT YOU",
    "HOW TO GET THE GIRL",
    "FOR BETTER",
    "FOR WORST",
    "KISSES ON CHICKS",
    "IS IT OVER NOW",
    "U THE GAME",

];


const arrayReputation = [
    "READY FOR THIS",
    "DELICATE",
    "LGB",
    "END GAME",
    "I DID SOMETHING BAD",
    "MY REPUTATIONS NEVER BEEN WORSE",
    "DONT BLAME ME",
    "SO IT GOES",
    "GORGEOUS",
    "GETAWAY CAR",
    "KING OF MY HEART",
    "DRESS",
    "NEW YEARS DAY",
    "BUZZ CUT",
    "REP ERA",
    "LETS GO BITCH",
    "BIG REP",
    "FLY LIKE A JETSTREAM",
    "NEVER TRUST A NARCISSIST",
    "LORD SAVE ME",
    "YOUR DAISY",
    "I WAS POISON IVY",
    "LIGHT ME UP"

];

const arrayLover = [
    "THE ARCHER",
    "JANUARY",
    "LONDON BOY",
    "CORNELIA ST",
    "AFTERGLOW",
    "CRUEL SUMMER",
    "LOVER",
    "THE MAN",
    "I THINK HE KNOWS",
    "MISS AMERINACA",
    "HEARTBREAK PRINCE",
    "PAPER RINGS",
    "FALSE GOD",
    "ME",
    "NICE TO HAVE A FRIEND",
    "DAYLIGHT",
    "BAD BAD GIRL",
    "NO RULES",
    "ANGELS ROLL THEIR EYES",
    "CRYED LIKE A BABY",
    "MIJIJI",
    "OVER DRAMATIC",
    "PLAY STUPID GAMES",
    "SHINY THINGS",
];

const arrayFolklore = [
    "THIS IS ME TRYING",
    "AUGUST",
    "SALT AIR",
    "TO SATURN",
    "TO THE MOON",
    "SEVEN",
    "PICTURE ME",
    "MIRRORBALL",
    "SHINING JUST FOR YOU",
    "HOAX",
    "PEACE",
    "BETTY",
    "JAMES",
    "FOLKWHORE",
    "THE ONE",
    "EXILE",
    "CARDIGAN",
    "MY TEARS RICOCHET",
    "ILICIT AFFAIRS",
    "INVISIBLE STRING",
    "TYING YOU TO ME",
    "IM ON SOME NEW SHIT",
    "MAD WOMAN",
    "EPIPHANY",
    "AURORAS & SAD PROSE",
    "THE LAKES",
    "WASTED POTENTIAL",
    "MADDEST WOMAN",
    "KEY LIME GREEN",
    "RUNNING LIKE WATER",
    "CURSING MY NAME",
    "BUT I DIDNT POUR THE WHISKEY",
    "DONT CALL ME KID",
    "RUMOURS FROM INEZ",
    "NO OTHER SHADE OF BLUE",
    "TO LIVE",
    "FOR THE HOPE",
    "OF IT ALL",
    "PURPLE PINK SKIES",
    "RUINNING EVERYTHING",
];

const arrayEvermore = [
    "WILLOW",
    "TAKE MY HAND",
    "CHAMPAGNE PROBLEMS",
    "SHES FUCKED IN THE HEAD",
    "GOLD RUSH",
    "TIS THE DAMN SEASON",
    "NO BODY",
    "NO CRIME",
    "TOLERATE IT",
    "HAPPINESS",
    "DOROTHEA",
    "MARJORIE",
    "CONEY ISLAND",
    "IVY",
    "YOUR IVY GROWS",
    "COVER ON YOU",
    "COWBOY LIKE ME",
    "LONG SHORT STORY",
    "CLOSURE",
    "EVERMORE",
    "HOUSE OF STONE",
    "SURVIVED",
    "WRECK MY PLANS",
    "RIGHT WERE YOU LEFT ME",
    "STILL IN THE RESTAURANT",
    "TIME TO GO",
    "EAGLES",
    "DUST COLLECTED",
    "CLEVER KIND",
    "STILL TWENTY THREE",
    "THE GIRL WHO LIVES IN DELUSION",
    "DELUSION",
];


const arrayMid = [
    "SEXY BABY",
    "SPIDER BOY",
    "KARMA",
    "KARMA IS A CAT",
    "I DONT START SHIT",
    "SHIMMER",
    "DRAW THE CAT EYE",
    "GET EVEN",
    "I MISS SPARKLING",
    "YOU CAN FACE THIS",
    "HITS DIFFERENT",
    "FAIL TO PLAN",
    "KARMA IS MY BFF",
    "LAVENDER HAZE",
    "MEET ME AT MIDNIGHT",
    "SUNSHINE",
    "MIDNIGHT RAIN",
    "MAROON",
    "ANTI HERO",
    "ITS ME HI",
    "IM THE PROBLEM",
    "TAKE THE MOMENT AND TASTE IT",
    "QUESTION",
    "VIGILANTE SHIT",
    "GOOD GIRL",
    "BIG CITY",
    "SAD BOY",
    "BEJEWELD",
    "LABYRINTH",
    "MASTERMIND",
    "SNOW AT THE BEACH",
    "GLITCH",
    "DEAR READER",
    "PARIS",
    "THE GREAT WAR",
    "PATHOLOGICAL PEOPLE PLEASER",
    ""
];


const arraySilabas = [
    "TOSOTD", //--- Fearless
    "YBWM", // -- FEARLESs
    "ATWTMVTVFTV", // RED   
    "WANEGBT",
    "OOTW", // 1989
    "AYHTDWS", // 1989
    "WTNY", // 1989
    "IWIW",
    "YGTG", // 1989
    "TIABFTD", //1989
    "NTWDT",
    "TIWWCHNT", // REP
    "LWYMMD", // REP
    "ZZZZ", // REP
    "KOMH", // REP
    "RATATA", // REP
    "YNTCD", // LOVER
    "DBATC", // LOVER
    "IDK", // LOVER
    "ITHK", //  LOVER
    "MAATHP", // LOVER
    "TLAGD", // FOLKLORE
    "LSS", // EVERMORE  
    "RWYLM", //EVERMORE
    "TSEM", // EVERMORE
    "YOYOK", // MID
    "SATB", // MID
    "BTTHS", // MID
    "WVCVSV",// MID
    "APTW",
];

const arraySabrina = [
    "READ UR MIND",
    "FEATHER",
    "VICIOUS",
    "ALREADY OVER",
    "TORNADO WARNINGS",
    "OPPOSITE",
    "FAST TIMES",
    "BECAUSE I LIKED A BOY",
    "NONSENSE",
    "IM A SLUT",
    "IM HARD TOPIC ON YOUR THONGE",
];